server {
    listen 80;


    # Replace with your domain or Public IP if not using a domain
    server_name eb-public-alb-1364711755.us-east-2.elb.amazonaws.com;

    # 1. Forward API calls to the App Server Private IP
    # Backend: Node.js API (Running on Port 3001)
    # This routes all requests starting with /api to your backend
    location /api/ {
        proxy_pass http://10.0.9.240:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }



    # 2. Forward everything else to the local Next.js frontend
    # Frontend: Next.js (Running on Port 3000)
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Standard headers for real client IP tracking
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
